hipstersmoothie/storybook-dark-mode

src/Tool.tsx
**What does this PR do?**
This PR fixes a bug related to the moment in which we navigate through stories with a theme different to the base configured theme.
In order to fix it we will subscribe to another event that will trigger the same exact logic that the one triggered on stories configured.
It fixes issue: https://github.com/hipstersmoothie/storybook-dark-mode/issues/9
=> Subscribed to another event in order to trigger theme change on story change

src/Tool.tsx
This allows the plugin to work on the docs pages from the new [`addon-docs`](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf).
=> Listen for `docsRendered` event so it also picks up the correct theme.

README.md, package.json, src/Tool.tsx, src/constants.ts, src/index.tsx
Allows any component to use the hook in their Component to fetch the current state of dark-mode.
Here I'm using the hook to set the `theme` on a monoco editor in the addons panel
=> Create a React hook for getting dark-mode state

src/Tool.tsx
I was getting this error in my storybook for a svelte project:
```
TypeError: Cannot use 'in' operator to search for 'parameters' in undefined
at renderTheme (vendors~main.44b08c472af3b68560ea.bundle.js:204953)
```
I added a check to see if the current story data is undefined before checking if it contains the "parameters" key.
I'm not sure why getCurrentStoryData() is returning null, but now renderTheme() can handle it.
=> Fix undefined story data

src/Tool.tsx, src/register.tsx
=> Add toggle button to to docs page and save custom themes on initilization

README.md, src/Tool.tsx
This PR makes the work done in #102 optional and off by default. It also applies the dark/light class to the manager. 
<details>
<summary>📦 Published PR as canary version: <code>0.5.1-canary.107.1984.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```sh
npm install storybook-dark-mode@0.5.1-canary.107.1984.0
yarn add storybook-dark-mode@0.5.1-canary.107.1984.0
```
</details>
=> add dark/light class to manager + optionally set classes on the preview

.gitignore, src/Tool.tsx, src/index.tsx
Read default isDark value for `useDarkMode` hook from local storage.
Fixes #109.
=> useDarkMode: read default isDark value from local storage

src/Tool.tsx
It looks like the story params update with the brand after the first render. This PR adds an effect that will update the store if the params change
<details>
<summary>📦 Published PR as canary version: <code>1.0.1-canary.121.2504.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```sh
npm install storybook-dark-mode@1.0.1-canary.121.2504.0
yarn add storybook-dark-mode@1.0.1-canary.121.2504.0
```
</details>
=> Fixing brand theming in light mode

package.json
The `dist/` contains source-maps, but the underlying source files aren't present which causes webpack to complain 
```
WARNING in ./node_modules/storybook-dark-mode/dist/icons/Moon.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/icons/Moon.tsx': Error: Can't resolve '../../src/icons/Moon.tsx' in '/Users/adierkens/Developer/rewrite/web/node_modules/storybook-dark-mode/dist/icons'
@ ./node_modules/storybook-dark-mode/dist/Tool.js 59:29-52
@ ./node_modules/storybook-dark-mode/dist/index.js
@ ./packages/storybook/dist/esm/addons/docs/index.js
@ ./packages/storybook/dist/esm/addons/index.js
@ ./packages/storybook/dist/esm/index.js
@ ./.storybook/config.js
@ …
```
=> Ship source files for sourcemaps

README.md, package.json, preset.js
<details>
<summary>📦 Published PR as canary version: <code>1.0.4-canary.129.2979.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```sh
npm install storybook-dark-mode@1.0.4-canary.129.2979.0
yarn add storybook-dark-mode@1.0.4-canary.129.2979.0
```
</details>
=> add preset.js

README.md
In newest versions of Storybook it looks like presets changed to the addons field inside `.storybook/main.js` config file
=> Change presets field to addons in configuration

README.md
"themes" import origin should be explicitly specified, as preview.js use is fully optional when using Storybook.
=> README: added "themes" import origin

src/register.tsx
When setting initial theme extends from default storybook themes to account for new variables that aren't yet stored it localStorage from saved theme. This will be overriden once the plugin actually loads
closes #140
<details>
<summary>📦 Published PR as canary version: <code>1.0.5-canary.142.3135.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```sh
npm install storybook-dark-mode@1.0.5-canary.142.3135.0
yarn add storybook-dark-mode@1.0.5-canary.142.3135.0
```
</details>
=> Fix "color function invalid arg" issue when upgrading between versions of storybook

README.md, src/Tool.tsx
Add a new parameter `classTarget`, which can be set to define where the dark class should be toggled inside the iframe document. Defaults to existing functionality, toggling the class on the iframe's `body`.
Closes #133.
=> Add parameter for classTarget to toggle iframe preview class

package.json
Current semver range in the `peerDependencies` for storybook gives the following warnings:
```
warning " > storybook-dark-mode@1.0.7" has unmet peer dependency "@storybook/addons@>= 6.x".
warning " > storybook-dark-mode@1.0.7" has unmet peer dependency "@storybook/api@>= 6.x".
warning " > storybook-dark-mode@1.0.7" has unmet peer dependency "@storybook/components@>= 6.x".
warning " > storybook-dark-mode@1.0.7" has unmet peer dependency "@storybook/core-events@>= 6.x".
warning " > storybook-dark-mode@1.0.7" has unmet peer dependency "@storybook/theming@>= 6.x".
```
I think `>= 6.x` is invalid semver range --> changed to `^6.0.0`.
=> Fix storybook peerDependencies semver range

src/index.tsx, src/register.tsx
It's [recommended](https://github.com/storybookjs/storybook/blob/0981b635eed95b48998b9a5fd6d67216802324fb/lib/addons/src/public_api.ts#L3) to use named imports for @storybook/addons, and in fact the default import causes problems with the vite storybook builder.  The testing I did was copying this change into my local project and confirming the vite builder worked correctly.
=> Import addon as named

README.md
Change `export parameters` to `export const parameters` in README
closes #153
=> Change export parameters to export const parameters in README

package.json, src/Tool.tsx, typings/global.d.ts
I'm not sure what has changed on Storybooks side but using this addon with storybook 6.5.10 appears to cause the following error when starting storybook:
```shell
WARN   Failed to load preset: {"type":"presets","name":"/Users/jackwestbrook/Projects/grafana/.yarn/__virtual__/storybook-dark-mode-virtual-ad5eee07b7/0/cache/storybook-dark-mode-npm-1.1.0-3820b02cd6-e1d7abbb96.zip/node_modules/storybook-dark-mode/dist/index.js"} on level 1
ERR! ReferenceError: window is not defined
ERR!     at Object.<anonymous> (/Users/jackwestbrook/Projects/grafana/.yarn/__virtual__/storybook-dark-mode-virtual-ad5eee07b7/0/cache/storybook-dark-mode-npm-1.1.0-3820b02cd6-e1d7abbb96.zip/node_modules/storybook-dark-mode/src/Tool.tsx:40:28)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1103:14) …
```
=> Fix: Storybook preset loading error

package.json, yarn.lock
This pull request addresses #183.
The `@storybook/*` dependencies were moved from `peerDependencies` to `dependencies`, like it's done in other addons ([@storybook/addon-actions](https://github.com/storybookjs/storybook/blob/bf98ade4ca2067ddd23dfbf4cd65e19b889fa9ea/addons/actions/package.json#L44-L50), [@storybook/addon-a11y](https://github.com/storybookjs/storybook/blob/8dd4fa6ef42f803ec276be18fb78644a827d5b74/addons/a11y/package.json#L48-L55), and many others).
The `react` and `react-dom` packages were also added to the peer dependencies, like it's done in other addons. I can remove this commit if you don't want it, let me know.
=> Remove @storybook/* dependencies from peer dependencies

src/Tool.tsx
Update to useEffect to use the store's `current` value first before the default `current` in parameters. This allows the current value to persist between page refreshes and story navigation.
=> Persist current store value

src/Tool.tsx
if not really using storybook theming and instead using CSS overrides there was a flash of unstyled content. this fixes it by setting the manager's them upon load
=> fix flash of unthemed storybook when using CSS overrides

src/Tool.tsx
Issue #206 
As described in the issue, the `current` param seems not to be respected.
When loading the Storybook with OS color schema as `dark`, a default `initialMode` is always created with the `dark` value, so the re-evaluation of the `current` param value never happens again.
I wrote my initial thoughts [here](https://github.com/hipstersmoothie/storybook-dark-mode/issues/206#issuecomment-1361209414) in the issue.
For this purpose, I added a new property in the store to explicitly control if the user has clicked in the theme handler. If so, we respect the user decision. If not, we respect the `current` param, and at the end we look at the preferred color schema.
Why a new property? I think relying on the `initialMode` is not safe because it is set from multiple side effects. Having a …
=> Fix: `current` param not being respected by the dark OS color mode

README.md, src/Tool.tsx
~~BREAKING CHANGE: `lightClass` and `darkClass` have changed from `string` to `string[]`. Before: `darkClass: 'my-dark-class'`, after: `darkClass: ['my-dark-class']`~~
=> feat: Add ability to toggle multiple light/dark classes

src/Tool.tsx
The motivation behind this is for storybook-dark-mode to work in a test environment (jest, vitest) without global config
=> Null check window.matchMedia

src/Tool.tsx
fixes #174 
seems like the moment you import any `storybook-dark-mode` into the preview side of things, `updateManager` is causes the body tag to have the classname put on it.
if we specify
```tsx
export const parameters = {
darkMode: {
classTarget: 'html'
},
};
```
Seems to me that what we really want is that only the `html` tag be manipulated.
=> fix: use classTarget when updating manager too

README.md
In storybook v7, addons is exposed via the `@storybook/preview-api` package. See https://storybook.js.org/docs/react/addons/addons-api for more details.
=> Update addons import in readme code examples

examples/basic/src/Button.stories.d.ts, examples/basic/src/Button.stories.tsx, examples/basic/src/useDarkMode.stories.tsx, src/index.tsx
Regression in v4.0.0, `useDarkMode` updates no longer propagate to the preview frame. Seems `addons` should be imported from `preview-api` and not `manager-api`. See added story to reproduce.
=> Fix `useDarkMode` to use correct channel

src/index.tsx
I'm using a custom decorator to set the `data-theme` attribute in the `html` element:
```jsx
// .storybook/preview.tsx
export const decorators = [
(Story: ComponentType) => {
const isDarkMode = useDarkMode();
useEffect(() => {
document.documentElement.dataset.theme = isDarkMode ? 'dark' : 'light';
}, [isDarkMode]);
return <Story />;
},
];
```
When I add an interactivity to one of my components using hooks from `@storybook/preview-api`, for example the `useArgs`:
```jsx
export const Checkbox: Story = {
args: {
selected: false,
onClick: fn(),
},
render: (args) => {
const [{ selected }, updateArgs] = useArgs();
const onClick = (id: string) => {
updateArgs({ selected: !selected });
args.onClick();
};
return <Checkbox {...args} selected={selected} onClick={onClick} />;
},
};
```
Everything …
=> Fix for the "Storybook preview hooks can only be called inside decorators and story functions." error
